Add: maintenance window support
Azure/terraform-azurerm-aks pull request #133
Opened 2021-12-02 08:49 UTC by nlamirault

This PR add support for https://docs.microsoft.com/en-us/azure/aks/planned-maintenance

2022-01-19 07:26 UTC, nlamirault commented
@jcorioland Any news for this feature ?

2022-01-19 07:37 UTC, jcorioland commented
@nlamirault I am contributor on this project, but I can't review/merge PR, sorry.

2022-01-19 08:10 UTC, nlamirault commented
ok @jcorioland .
Project seems not maintained ? Last commit is yours (2021/05/27)

2022-01-24 03:17 UTC, lonegunmanb commented
> ok @jcorioland . Project seems not maintained ? Last commit is yours (2021/05/27)

Hi @nlamirault , @jcorioland was a contributor and his's pr was accepted and merged by the project's owner.

2022-03-04 06:47 UTC, nlamirault commented
Could you review this PR @yupwei68 please ?

2022-04-22 06:43 UTC, lonegunmanb commented
Hello @nlamirault , thanks for your pr! I'd like to merge this pr, but now we have conflicts to resolve, and I've left some comments, would you please take a look and push again? Thanks!

2022-05-18 01:58 UTC, lonegunmanb requested changes

2022-05-30 08:15 UTC, nlamirault commented on main.tf
> +      for_each = var.enable_maintenance_window == true ? var.maintenance_allowed : []
Done

2022-05-30 08:16 UTC, nlamirault commented on main.tf
> +      for_each = var.enable_maintenance_window == true ? var.maintenance_not_allowed : []
Done

2022-05-30 08:17 UTC, nlamirault commented on variables.tf
> +    hours = list(string)
Done

2022-05-31 00:35 UTC, lonegunmanb requested changes
Hi, I've tested the code with fixture in the test folder, and the following error occurred:

```txt
│ Error: Missing required argument
│
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on ..\..\main.tf line 88, in resource "azurerm_kubernetes_cluster" "main":
│   88:   maintenance_window {
│
│ "maintenance_window.0.allowed": one of `maintenance_window.0.allowed,maintenance_window.0.not_allowed` must be specified
╵
╷
│ Error: Missing required argument
│
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on ..\..\main.tf line 88, in resource "azurerm_kubernetes_cluster" "main":
│   88:   maintenance_window {
│
│ "maintenance_window.0.not_allowed": one of `maintenance_window.0.allowed,maintenance_window.0.not_allowed` must be specified
╵
```

The `enable_maintenance_window` default value `false` will emit an empty `maintenance_window` block which is not valid. Would the following code be better?:

```hcl
dynamic "maintenance_window" {
    for_each = var.enable_maintenance_window ? ["maintenance_window"] : []
    content {
      dynamic "allowed" {
        for_each = var.maintenance_allowed
        content {
          day   = allowed.value.day
          hours = allowed.value.hours
        }
      }

      dynamic "not_allowed" {
        for_each = var.maintenance_not_allowed
        content {
          start = not_allowed.value.start
          end   = not_allowed.value.end
        }
      }
    }
  }
```

2022-09-26 11:09 UTC, zioproto commented
@nlamirault this PR does not merge anymore in the current master. Please rebase this work asap or look into the proposed #256

2022-09-27 08:32 UTC, lonegunmanb commented
That's ok @zioproto, I'm working on a new pr for this feature, I'll submit it when it's ready.

Btw, in my new pr, I'd like to use [`optional`](https://www.terraform.io/language/expressions/type-constraints#optional-object-type-attributes) feature introduced by Terraform 1.3, which requires we upgrade Terraform Core's restriction to `>= 1.3`. Do you think such a change is a breaking change? If so, I'd like to defer this pr to our next new major release, maybe after we solve all the remaining prs.

2022-09-30 08:00 UTC, lonegunmanb commented
Thanks @nlamirault for open this pr, I'm closing it in favor of #256 has brought us this feature. Thanks for your contribution to this module.

2022-09-30 08:00 UTC, closed without merging

2022-09-30 10:12 UTC, nlamirault commented
@lonegunmanb :+1: