feat(aks): add microsoft defender support
Azure/terraform-azurerm-aks pull request #232
Opened 2022-08-23 14:49 UTC by eyenx

Changes proposed in the pull request:

Adds support for a `microsoft_defender` block introduced with https://github.com/hashicorp/terraform-provider-azurerm/pull/16218/

Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

2022-08-27 07:49 UTC, eyenx commented
@lonegunmanb can't run the test anymore. 

Always getting same errors:

```
INFO: Styling Terraform configurations...
INFO: Done!
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported block type

  on main.tf line 5:
   5: moved {

Blocks of type "moved" are not expected here.


Error: Unsupported block type

  on main.tf line 178, in resource "azurerm_kubernetes_cluster" "main":
 178:     precondition {

Blocks of type "precondition" are not expected here.


Error: Unsupported block type

  on main.tf line 182, in resource "azurerm_kubernetes_cluster" "main":
 182:     precondition {

Blocks of type "precondition" are not expected here.


Error: Unsupported argument

  on variables.tf line 57, in variable "agents_pool_name":
  57:   nullable    = false

```

The `terraform-test` image we are using is quite outdated (versoin 0.14.4). Could it be because of that?

2022-08-27 08:03 UTC, eyenx commented
I now created my own `mcr.microsI was able to run the tests with it:
oft.com/terraform-test:1.2.5`  by grabbing the github.com/azure/terraform-test repo and adjusting some vars. 

I was able to run the rake build, but not the tests:

```
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
INFO: Linting Terraform configurations...
INFO: Done!
INFO: Styling Terraform README...
INFO: Done!
INFO: Styling Terraform fixture configurations...
INFO: Done!
go: cannot find main module, but found Gopkg.lock in /go/src/terraform-azurerm-aks
        to create a module there, run:
        go mod init
rake aborted!
ERROR: Go test failed!

/go/src/terraform-azurerm-aks/Rakefile:45:in `block (2 levels) in <top (required)>'
Tasks: TOP => full => e2e => integration:test
(See full trace by running task with --trace)
```

2022-08-29 02:53 UTC, lonegunmanb commented
> I now created my own `mcr.microsoft.com/terraform-test:1.2.5` by grabbing the https://github.com/azure/terraform-test repo and adjusting some vars.
> 
> I was able to run the rake build, but not the tests:
> 
> ```
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> INFO: Linting Terraform configurations...
> INFO: Done!
> INFO: Styling Terraform README...
> INFO: Done!
> INFO: Styling Terraform fixture configurations...
> INFO: Done!
> go: cannot find main module, but found Gopkg.lock in /go/src/terraform-azurerm-aks
>         to create a module there, run:
>         go mod init
> rake aborted!
> ERROR: Go test failed!
> 
> /go/src/terraform-azurerm-aks/Rakefile:45:in `block (2 levels) in <top (required)>'
> Tasks: TOP => full => e2e => integration:test
> (See full trace by running task with --trace)
> ```

Thanks @eyenx for opening this Pr! The dockerfile and docker imaged described in readme file is outdated and no longer been maintained, we're working on a new CI pipeline and we're close to a release (We'll release v6.0.0 with this new CI pipeline). I'm not going to update this `mcr.microsoft.com/terraform-test` image and rake tests since they'll be replaced very soon. If you're interested in this new CI, you can try it on my [personal branch](https://github.com/lonegunmanb/terraform-azurerm-aks/tree/ci), we have instructions in readme file on how to run the pr checks and acc tests for our module. For this pr please give me some time to review and test with new CI on my machine. Once we've solved the issues that block our CI pipeline, we'll introduce this pipeline into some legacy azurerm Terraform modules. Thanks for your understanding.

2022-08-31 01:56 UTC, lonegunmanb requested changes

2022-08-31 05:03 UTC, eyenx commented on main.tf
> +  dynamic "microsoft_defender" {
gonna do this ra

2022-08-31 05:04 UTC, eyenx commented on variables.tf
> +variable "microsoft_defender_enabled" {
gonna do this ra

2022-08-31 05:09 UTC, eyenx commented on main.tf
> +  dynamic "microsoft_defender" {
done

2022-08-31 05:09 UTC, eyenx commented on variables.tf
> +variable "microsoft_defender_enabled" {
done

2022-09-01 10:49 UTC, lonegunmanb requested changes

2022-09-06 09:08 UTC, eyenx commented on main.tf
> +      log_analytics_workspace_id = var.log_analytics_workspace_id == null ? azurerm_log_analytics_workspace.main[0].id : var.log_analytics_workspace.id
Done. Sry for late reply

2022-09-07 05:55 UTC, lonegunmanb approved these changes
Thanks @eyenx, LGTM

2022-09-07 05:55 UTC, merged