Add Network Contributor role assignments scoped to AKS nodepools subnets
Azure/terraform-azurerm-aks pull request #327
Opened 2023-03-16 13:51 UTC by zioproto

This PR creates a role assignment for the AKS Service Principal to be a Network Contributor on the subnets used for the AKS Cluster.

The AKS cluster identity has the Contributor role on the AKS second resource group (MC_myResourceGroup_myAKSCluster_eastus)
In this case no additional change is necessary.

However when using a custom VNET, the AKS cluster identity needs the Network Contributor role on the VNET subnets
used by the system node pool and by any additional node pools.
Docs:
* https://learn.microsoft.com/en-us/azure/aks/configure-kubenet#prerequisites
* https://learn.microsoft.com/en-us/azure/aks/configure-azure-cni#prerequisites

This PR detects if a custom VNET is used looking at the values of the variable `var.vnet_subnet_ids` and at the value of `vnet_subnet_ids` in the map variable of the node pools.

## Issue number

Fixes #178 

## Checklist before requesting a review
- [X] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [X] I have executed pre-commit on my machine
- [X] I have passed pr-check on my machine

2023-03-17 02:23 UTC, lonegunmanb requested changes
Thanks for opening this pr @zioproto!. Almost LGTM but only a few issues. It would be nice if we can assign this new variable in `multiple_node_pools` example.

2023-03-17 02:23 UTC, lonegunmanb commented on locals.tf
> +  vnet_subnet_ids = toset(flatten(concat([
Could we rename it to `subnet_ids`?

2023-03-17 15:12 UTC, zioproto commented on variables.tf
> +  default     = false
I added `nullable = false`, but I would like to keep the `false` default value. I dont want to introduce a change in the default behaviour.

2023-03-21 08:31 UTC, lonegunmanb commented
Hi @zioproto this pr almost LGTM but it's base version contains a failed example that was fixed by #328, would you please rebase this pr to the latest main branch and try again? Thanks!

2023-03-21 10:21 UTC, zioproto commented
Rebased on current `origin/main`. Thanks

2023-03-24 01:16 UTC, lonegunmanb approved these changes
Thanks @zioproto, LGTM! 🚀

2023-03-24 01:17 UTC, merged