make prefix variable optional
Azure/terraform-azurerm-aks pull request #359
Opened 2023-04-26 20:41 UTC by withersj888

## Describe your changes

When providing a name for the Log Analytics Workspace (var.cluster_log_analytics_workspace_name) and a DNS prefix is not required for the cluster (dns_prefix argument within azurerm_kubernetes_cluster.main), the prefix variable is not required and should therefore be made optional.

## Issue number

#308 

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [x] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

Thanks for your cooperation!

2023-04-26 20:43 UTC, withersj888 commented
@microsoft-github-policy-service agree

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: 26 April 2023 21:41
To: ***@***.***>
Cc: Jay ***@***.***>; ***@***.***>
Subject: Re: [Azure/terraform-azurerm-aks] make prefix variable optional (PR #359)


@withersj888<https://github.com/withersj888> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree [company="{your company}"]

Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree

  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"
Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement (“Agreement”) is agreed to by the party signing below (“You”),
and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your
contributions to Microsoft open source projects. This Agreement is effective as of the latest signature
date below.

  1.  Definitions.
“Code” means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to Microsoft under this Agreement.
“Project” means any of the projects owned or managed by Microsoft and offered under a license
approved by the Open Source Initiative (www.opensource.org<http://www.opensource.org>).
“Submit” is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”
“Submission” means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.
  2.  Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.
  3.  Originality of Work. You represent that each of Your Submissions is entirely Your original work.
Should You wish to Submit materials that are not Your original work, You may Submit them separately
to the Project if You (a) retain all copyright and license information that was in the materials as You
received them, (b) in the description accompanying Your Submission, include the phrase “Submission
containing materials of a third party:” followed by the names of the third party and any licenses or other
restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
guidelines concerning Submissions.
  4.  Your Employer. References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.
  5.  Licenses.

  *   Copyright License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
parties.
  *   Patent License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.
  *   Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

  1.  Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
  2.  Notice to Microsoft. You agree to notify Microsoft in writing of any facts or circumstances of which
You later become aware that would make Your representations in this Agreement inaccurate in any
respect.
  3.  Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.
  4.  Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
defenses of lack of personal jurisdiction and forum non-conveniens.
  5.  Entire Agreement/Assignment. This Agreement is the entire agreement between the parties, and
supersedes any and all prior agreements, understandings or communications, written or oral, between
the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

—
Reply to this email directly, view it on GitHub<https://github.com/Azure/terraform-azurerm-aks/pull/359#issuecomment-1524019125>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIODUVFA3ZPXI6WKHA7MXF [...]

2023-04-27 05:25 UTC, lonegunmanb commented
Hi @withersj888 thanks for opening this pr, since it looks like a non-breaking change I'd like to defer it to 7.1.0 so we can verify that this pr won't introduce any breaking or surprise change to this module. Our next release is 7.0.0 and I'd like to put all breaking changes in this release, we'll skip the test for breaking changes, that's why we'd like to defer this pr.

Again, thanks for your contribution, I'll deal with your proposal right after we've released the 7.0.

2023-04-27 06:31 UTC, withersj888 commented
Hi @lonegunmanb, no worries, glad i could contribute.
I see the prepr-check has failed, but i'm not sure how to fix it - I ran make precommit before the PR.

2023-04-28 01:13 UTC, lonegunmanb commented
@withersj888 This pr made `var.prefix` an optional variable, and our pipeline is enforcing a [sorting rule](https://github.com/Azure/terraform-azure-modules/blob/main/codex/logic_code/variables.tf.md#order-to-define-variable), so we need move this `var.prefix` to the right place.

I'm working on an [autofix](https://github.com/lonegunmanb/azure-verified-module-fix) tool that could sort tf code after a pr has been merged so we won't be bothered to take care of such things any more, but for now we need sort code manually.

2023-04-28 07:09 UTC, zioproto commented
@withersj888 look at this section of the README:
https://github.com/Azure/terraform-azurerm-aks#pre-commit--pr-check--test

you need to start with the `pre-commit`:
```
$ docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:latest make pre-commit
```

2023-04-28 07:32 UTC, lonegunmanb requested changes
Hi @withersj888 thanks for the update, we might need to move `var.resource_group_name` back to pass the `pr-check`.

2023-04-28 07:32 UTC, lonegunmanb commented on variables.tf
> +variable "resource_group_name" {
`resource_group_name` is still a required variable so we should move it back to the original place.

2023-04-28 07:38 UTC, withersj888 commented
Ah, OK. I realise now that the variables are ordered by required and optional and then alphabetical.

________________________________
From: lonegunmanb ***@***.***>
Sent: Friday, April 28, 2023 8:33:08 AM
To: Azure/terraform-azurerm-aks ***@***.***>
Cc: Jay Withers ***@***.***>; Mention ***@***.***>
Subject: Re: [Azure/terraform-azurerm-aks] make prefix variable optional (PR #359)


@lonegunmanb requested changes on this pull request.

Hi @withersj888<https://github.com/withersj888> thanks for the update, we might need to move var.resource_group_name back to pass the pr-check.

________________________________

In variables.tf<https://github.com/Azure/terraform-azurerm-aks/pull/359#discussion_r1180032737>:

> @@ -1013,6 +1009,11 @@ variable "rbac_aad_tenant_id" {
   default     = null
 }

+variable "resource_group_name" {


resource_group_name is still a required variable so we should move it back to the original place.

—
Reply to this email directly, view it on GitHub<https://github.com/Azure/terraform-azurerm-aks/pull/359#pullrequestreview-1405382309>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIODUVGWYW4NLBFDHU635LDXDNXDJANCNFSM6AAAAAAXM6L3NM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-06-05 02:26 UTC, lonegunmanb commented
I'm closing this pr in favor of #382 , thanks for your contribution @withersj888 !

2023-06-05 02:26 UTC, closed without merging