fix: correct wording of the doc
Azure/terraform-azurerm-aks pull request #461
Opened 2023-10-27 11:03 UTC by meysam81

2023-10-27 11:27 UTC, zioproto requested changes

2023-10-27 11:27 UTC, zioproto commented on README.md
> +| <a name="input_node_pools"></a> [node\_pools](#input\_node\_pools) | A map of node pools that need to be created and attached on the Kubernetes cluster. The key of the map can be the name of the no
This line is autogenerated from the `variables.tf` code. Can you fix the type in `variables.tf` ?

2023-10-27 12:52 UTC, meysam81 commented
> @meysam81 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

2023-10-27 12:53 UTC, meysam81 commented
@microsoft-github-policy-service agree company="Licenseware"

2023-10-30 05:55 UTC, zioproto approved these changes

2023-10-30 06:39 UTC, merged