Add `cost_analysis_enabled` option
Azure/terraform-azurerm-aks pull request #583
Opened 2024-08-19 21:53 UTC by artificial-aidan

## Describe your changes

Add the `cost_analysis_enabled` variable

## Issue number

#528

## Checklist before requesting a review
- [X] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [X] I have executed pre-commit on my machine
- [X] I have passed pr-check on my machine

Thanks for your cooperation!

2024-08-20 05:06 UTC, lonegunmanb requested changes
Thanks @artificial-aidan for opening this pr to us, one review comment.

2024-08-20 05:06 UTC, lonegunmanb commented on main.tf
> +  cost_analysis_enabled               = var.cost_analysis_enabled
According to [the document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#cost_analysis_enabled):

>The sku_tier must be set to `Standard` or `Premium` to enable this feature. 

Could we add a `precondition` [here](https://github.com/Azure/terraform-azurerm-aks/blob/main/main.tf#L626)?

```hcl
precondition {
  condition         = var.cost_analysis_enabled != true || (var.sku_tier == "Standard" || var.sku_tier == "Premium")
  error_message = "`sku_tier` must be either `Standard` or `Premium` when cost analysis is enabled."
}
```

2024-08-20 14:29 UTC, artificial-aidan commented
@microsoft-github-policy-service agree company="Artificial Inc"

2024-08-21 08:19 UTC, lonegunmanb approved these changes
Thanks @artificial-aidan , LGTM!

2024-08-21 08:19 UTC, merged